### ISSUE TITLE
Error while parsing the .cro files!

### ISSUE THREAD

**Issue by LucarioRanger** [Jisagi/PokeTool#1]
It's as it says in the title. Any help? This is for Omega ruby!

SS of the error if needed
![Capture](https://user-images.githubusercontent.com/68386215/87786826-aa428080-c808-11ea-9740-7d61159fc42e.PNG)

**Comment by Jisagi** [comment]
The romfs folder holds all the cro files. It only check for 3 in them (DllField, DllPoke3Select and DllBattle). They all exist if you correctly backed up your game. After randomization they are changed and then copied by Poketool. This error indicates, that none of those files are present. It looks like that either your selected game folder is incorrect or the whole process was done incorrectly. Please refer to the dumping part of the [guide](https://zetadesigns.github.io/randomizing-layeredfs.html) again.

**Comment by LucarioRanger** [comment]
So I re-did it fallowing the guide and that worked! But the only problem now is that the game doesn't patch. I have everything in the luma folder (that was created from poketool) but nothing is patched! Even I have it set to patch in config. I don't have the update data for any of the updates (if that matters). Any advice for that?

**Comment by Jisagi** [comment]
Not being able to patch the game isn't a Poketool problem. Either re-check the guide or ask on the nintendo homebrew discord for help.
